### PR TITLE
Badges

### PR DESCRIPTION
**Pull request by JeffFessler**
and update readme urls.
will need @ahwillia to authorize the code coverage tools for the badges to work.

### CODE REVIEW

**Comment by ahwillia** [comment]
@JeffFessler -- is this a webhook or something I need to setup? I'm happy to do it if it is just clicking a few buttons.

**Comment by JeffFessler** [comment]
if you go to https://codecov.io/gh or https://codecov.io and login with your github account, then you should be able add repos (like this one) that you want to have code coverage.  i think it is just a few clicks.

likewise for https://coveralls.io/

having just one of these coverage tools would be fine so if you find it is easier to get one rather than the other set up then it's fine.  after you've enabled it, i think i can make some minor code tweak that will trigger it to run.
thanks.

**Comment by ahwillia** [comment]
Coveralls looks enabled... codecov.io is giving me an access token that I'm not sure what to do with... Screenshotting the top of that page below

image

**Edit:** I see it says the token thing is "Not required on Travis-CI, CircleCI, AppVeyor, or Azure Pipelines for public repositories. "

**Comment by JeffFessler** [comment]
i've put in an innocuous PR (docstrings) that hopefully will trigger the codecov runs and then we'll see if it is working.  thanks!

**Pull request merged**
