### PR TITLE
Project.toml, tests, and travis updates

### PR DESCRIPTION
**Pull request by lstagner**
This supersedes PR #19

### CODE REVIEW

**Comment by lstagner** [comment]
@ahwillia if you install the [Registrator.jl](https://github.com/JuliaRegistries/Registrator.jl/#registrator) and the [TagBot](https://github.com/apps/julia-tagbot) applications we can easily register the package

**Comment by lstagner** [comment]
hmm...the sparse array tests fail on julia 1.0-1.1 but pass for julia 1.2-1.3 and I don't know why. Should we set the minimum julia version to 1.2?

**Comment by lstagner** [comment]
Ok I just added a version check to make the sparse tests pass. It shouldn't affect performance since the compiler should optimize out the if statement.

**Review by ahwillia — APPROVED** [review]

**Comment by ahwillia** [comment]
Thanks for this @lstagner. I have not been staying up to date with advances in Julia -- would you like me to give you push access to this repository so that you can help me keep things current?

cc @degleris1

**Comment by lstagner** [comment]
That would work though you may to install the apps I mentioned. An alternative is to put repo up for adoption. The JuliaNLSolvers Organization might be a good fit.

**Comment by ahwillia** [comment]
@pkofod -- what do you think of migrating this repo into JuliaNLSolvers so that you all can keep it up to date?

**Comment by pkofod** [comment]
> @pkofod -- what do you think of migrating this repo into JuliaNLSolvers so that you all can keep it up to date?

If I say no, will you come back and play with us? :)

**Comment by lstagner** [comment]
@pkofod are you willing to do it? If not @ahwillia can you give me write access so I can merge this branch.

**Comment by pkofod** [comment]
Yes, it's fine. As long as everyone is fine with me caring about design decisions, releases, etc .

**Comment by ahwillia** [comment]
Thanks @pkofod -- that all sounds good to me! What is the cleanest way to migrate it over?

@lstagner -- I'll give you write access right now just in case you need it for a short-term solution.

**Comment by lstagner** [comment]
Thanks. I will hold off trying to update the registry since I don't know how the ownership change will change things.

**Comment by pkofod** [comment]
> Thanks @pkofod -- that all sounds good to me! What is the cleanest way to migrate it over?

You can transfer it to JuliaNLSolvers (or me) in the settings tabs I think.

**Comment by ahwillia** [comment]
Done -- I tried to transfer to JuliaNLSolvers but didn't have permission, so I just requested a transfer to you @pkofod

**Comment by nignatiadis** [comment]
Minor bump :D. Is there any chance the transfer and registration of this package could still happen? It would be convenient as I would like to register a package that depends on this.

**Comment by ahwillia** [comment]
Looks like @pkofod still has to accept the transfer.

**Comment by nignatiadis** [comment]
Thanks @ahwillia! I will probably hard-include the code in my package until this is resolved.

@pkofod let me know if I can do anything to help with the move!

**Comment by ghost** [comment]
Hi @nignatiadis. Just an FYI the registration of this package has been completed.

**Comment by nignatiadis** [comment]
That is great! Thank you for letting me know @tsano430!

**Comment by JeffFessler** [comment]
@pkofod it still seems sensible to house this under JuliaNLSolvers.
https://github.com/JuliaNLSolvers
What still needs to be done to make that happen?

**Pull request merged**
