### PR TITLE
Pull request/3a13ed96

### PR DESCRIPTION
**Pull request by silenj**
Purpose: get rid of warnings, make the tests pass and make the code run on julia v0.5 and v0.6. I am not fluent in Julia yet so to be sure, pleas look at the code.

### CODE REVIEW

**Comment by ahwillia** [comment]
Thanks for the effort on cleaning this up. Before reviewing, I'd like to merge #3, which should also address many of these problems - @rdeits is there a timeframe for when that will be ready?

**Comment by rdeits** [comment]
Ah, sorry! #3 should be ready for review now

**Comment by silenj** [comment]
Hello,

A slow learner as I am, realized that most of my challenges are due to 
git and its behavior. Therefore I propose you skip my contribution at 
this stage. There are several inconsistencies in them which are there 
because I used them to pinpoint the errors. I will clean up this and 
learn how to use git properly... Sorry for the mess.

What breaks the testing routines is the behaviour of constants in 
Float32 or Float64. Therefore in the testing algorithms snippets from 
test/alspgrad.jl should be like this:


for T in (Float64, Float32)
     Wg = max.(rand(T, p, k) .- T(0.3), 0)
     Hg = max.(rand(T, k, n) .- T(0.3), 0)
....

end

For compatibility of julia 0.5 and julia 0.6 for the inner constructors 
I do not know how to proceed.

Regards Johan

**Comment by rdeits** [comment]
Getting inner constructors working properly in v0.5 and v0.6 requires a slightly different syntax. Check out: https://discourse.julialang.org/t/how-to-make-new-inner-constructor-syntax-compatible-with-0-5/2094 and https://github.com/JuliaLang/Compat.jl/issues/332

**Pull request closed without merging**
